{{- if .Values.vault_settings.gcp_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/keycloak-certs-endpoint/versions/latest" 
        fileName: "keycloak-certs-endpoint"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/workflow-v2/versions/latest" 
        fileName: "workflow-v2"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/new-validation-process/versions/latest" 
        fileName: "new-validation-process"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/csrf-protection-enabled/versions/latest" 
        fileName: "csrf-protection-enabled"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-app-secret-key/versions/latest"
        fileName: "app-secret-key"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_api_gateway.secretName }}
      type: Opaque
      data:
      - objectName: "app-secret-key"
        key: app-secret-key
      - objectName: "keycloak-certs-endpoint"
        key: keycloak-certs-endpoint
      - objectName: "workflow-v2"
        key: workflow-v2
      - objectName: "new-validation-process"
        key: new-validation-process
      - objectName: "csrf-protection-enabled"
        key: csrf-protection-enabled
{{- end }}
