apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-configmap
  labels:
    {{- include "deps-api-gateway.labels" . | nindent 4 }}
data:
    ENV: {{ .Values.api_gateway_settings.ENV }}

    AUTH_VERIFY_SSL: '{{ .Values.api_gateway_settings.AUTH_VERIFY_SSL }}'

    LOG_LEVEL: '{{ .Values.api_gateway_settings.LOG_LEVEL }}'
    DOCUMENTATION_ENABLED: '{{ .Values.api_gateway_settings.DOCUMENTATION_ENABLED }}'

    CORLEONE_URL: '{{ .Values.api_gateway_settings.CORLEONE_URL }}'
    PREPROCESS_URL: '{{ .Values.api_gateway_settings.PREPROCESS_URL }}'
    DOCUMENT_URL: '{{ .Values.api_gateway_settings.DOCUMENT_URL }}'
    DOCUMENT_TYPE_URL: '{{ .Values.api_gateway_settings.DOCUMENT_TYPE_URL }}'
    UNIFIER_URL: '{{ .Values.api_gateway_settings.UNIFIER_URL }}'
    EXTRACTION_URL: '{{ .Values.api_gateway_settings.EXTRACTION_URL }}'
    WORKFLOW_MANAGER_URL: '{{ .Values.api_gateway_settings.WORKFLOW_MANAGER_URL }}'
    IAM_URL: '{{ .Values.api_gateway_settings.IAM_URL }}'
    OCR_URL: '{{ .Values.api_gateway_settings.OCR_URL }}'
    PROTOTYPE_URL: '{{ .Values.api_gateway_settings.PROTOTYPE_URL }}'
    PARSING_URL: '{{ .Values.api_gateway_settings.PARSING_URL }}'
    ENRICHMENT_URL: '{{ .Values.api_gateway_settings.ENRICHMENT_URL }}'
    PROMPTER_URL: '{{ .Values.api_gateway_settings.PROMPTER_URL }}'
    HIGH_SPARROW_URL: '{{ .Values.api_gateway_settings.HIGH_SPARROW_URL }}'
    OUTPUT_EXPORTING_URL: '{{ .Values.api_gateway_settings.OUTPUT_EXPORTING_URL }}'
    VALIDATION_URL: '{{ .Values.api_gateway_settings.VALIDATION_URL }}'
    AI_FUSION_URL: '{{ .Values.api_gateway_settings.AI_FUSION_URL }}'
    TEMPLATE_URL: '{{ .Values.api_gateway_settings.TEMPLATE_URL }}'
    GROUPS_URL: '{{ .Values.api_gateway_settings.GROUPS_URL }}'
    CLASSIFICATION_URL: '{{ .Values.api_gateway_settings.CLASSIFICATION_URL }}'
    CLOUD_NATIVE_EXTRACTION_URL: '{{ .Values.api_gateway_settings.CLOUD_NATIVE_EXTRACTION_URL }}'
    STORAGE_URL: '{{ .Values.api_gateway_settings.STORAGE_URL }}'
    DEFAULT_STORAGE: '{{ .Values.api_gateway_settings.DEFAULT_STORAGE }}'
    FILES_BATCH_URL: '{{ .Values.api_gateway_settings.FILES_BATCH_URL }}'
    EVENT_RELAY_URL: '{{ .Values.api_gateway_settings.EVENT_RELAY_URL }}'
    AGENTIC_AI_URL: '{{ .Values.api_gateway_settings.AGENTIC_AI_URL }}'
    FILE_URL: '{{ .Values.api_gateway_settings.FILE_URL }}'
    META_AGENT_URL: '{{ .Values.api_gateway_settings.META_AGENT_URL }}'
    SEMANTIC_PARSING_URL: '{{ .Values.api_gateway_settings.SEMANTIC_PARSING_URL }}'

    AUTHORIZATION_ENABLED: '{{ .Values.api_gateway_settings.AUTHORIZATION_ENABLED }}'

    # Telemetry
    INSTRUMENTATION_ENABLED: '{{ .Values.api_gateway_settings.INSTRUMENTATION_ENABLED }}'
    SERVICE_NAME: '{{ .Values.api_gateway_settings.SERVICE_NAME }}'
    EXPORTER_TYPE: '{{ .Values.api_gateway_settings.EXPORTER_TYPE }}'

    SERVICES: '{{ .Values.api_gateway_settings.SERVICES }}'
