api_gateway:
  image:
    path: "/deps-presale-x01/deps-api-gateway"
    pullPolicy: Always
  resources: {}
#    limits:
#      cpu:
#      memory:
#    requests:
#      cpu:
#      memory:

api_gateway_settings:
  ENV: presale
  LOG_LEVEL: "INFO"

helm:
  enabled: false

csi:
  vault_namespace: 'k8s-presale'
  roleName: 'k8s-presale'
  vaultKubernetesMountPath: 'kubernetes-presale'

service_account:
  serviceAccountName: 'deps-presale'
