api_gateway:
  image:
    path: "/deps-platform/deps-api-gateway"
  resources: {}
#    limits:
#      cpu: 700m
#      memory: 600Mi
#    requests:
#      cpu: 600m
#      memory: 500Mi

api_gateway_settings:
  ENV: staging
  LOG_LEVEL: "INFO"
  DEFAULT_STORAGE: S3_STORAGE

helm:
  enabled: false

csi:
  vault_namespace: 'k8s-staging'
  roleName: 'k8s-staging'
  vaultKubernetesMountPath: 'kubernetes-staging'

service_account:
  serviceAccountName: 'deps-staging'
