api_gateway:
  image:
    path: "/deps-platform/deps-api-gateway"
  resources: {}
#    limits:
#      cpu:
#      memory:
#    requests:
#      cpu:
#      memory:

api_gateway_settings:
  ENV: ds
  LOG_LEVEL: "INFO"

helm:
  enabled: false

csi:
  vault_namespace: 'k8s-ds'
  roleName: 'k8s-ds'
  vaultKubernetesMountPath: 'kubernetes-ds'

service_account:
  serviceAccountName: 'deps-ds'
