api_gateway:
  image:
    path: "/deps-platform/deps-api-gateway"
  resources: {}
#    limits:
#      cpu:
#      memory:
#    requests:
#      cpu:
#      memory:

api_gateway_settings:
  ENV: other
  LOG_LEVEL: "INFO"

helm:
  enabled: false
